# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://damianhagge.com
title: Damian Hagge
email: me@damianhagge.com
author: Damian Hagge
description: > # "Write an awesome description for your new site here. 
  Damian Hagge - freelance software engineer in Phoenix, Arizona. 
  Mobile, Big Data, Machine Learning, Cloud, Full Stack, Technial Strategy
copyright: 'Copyright &copy; 2016 Damian Hagge. All Rights Reserved.'
credits: 'Damian Hagge is a software engineer in Phoenix, AZ. He is currently co-founder 
and CTO of mobile healthcare payments startup <a href="http://cuesquared.com/">Cue2</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

gems: 
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty

# pagination
paginate: 4
paginate_path: "/blogs/page:num"


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/damian-hagge-7187a7
  - icon: envelope
    title: email
    url: mailto:contact@damianhagge.com
  - icon: github
    title: github
    url: https://github.com/dhagge
  - icon: twitter
    title: twitter
    url: https://twitter.com/DamianHagge